<Project Sdk="Microsoft.NET.Sdk.Razor">

  <Import Project="..\Lombiq.Tailwind.Targets\Lombiq.Tailwind.Targets.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OrchardCore.Theme.Targets" Version="3.0.0-preview-18975" />
    <PackageReference Include="OrchardCore.ContentManagement" Version="3.0.0-preview-18975" />
    <PackageReference Include="OrchardCore.DisplayManagement" Version="3.0.0-preview-18975" />
    <PackageReference Include="OrchardCore.ResourceManagement" Version="3.0.0-preview-18975" />
  </ItemGroup>

  <Import Project="..\Lombiq.Tailwind.Targets\Lombiq.Tailwind.Targets.targets" />

</Project>
